### ISSUE TITLE
Enhange Profile Settings + Email/PasswordAuth

### ISSUE THREAD

**Issue by severinlandolt** [jackquinlan/blueprint#16]
Hey @jackquinlan, very nice project and great choice of your stack.

I just had a look around, and I was thinking of two additions:

Profile Settings: Delete My account
Auth: Email/password option for login

**Comment by jackquinlan** [comment]
Thanks for the suggestion! I am going to be adding resend email functionality and I think credentials login/signup + password reset functionality is a great example to use.

**Comment by jackquinlan** [comment]
Just released the new features. Let me know what you think!

**Comment by severinlandolt** [comment]
How wow! Just took a look, it's great, well done ✨
