### ISSUE TITLE
is tRPC really needed?

### ISSUE THREAD

**Issue by mohsen1** [jackquinlan/blueprint#20]
I did a little of experimentation with removing tRPC and relying on React Server Components for this project and it works just fine. I'm curious to know if there is something that tRPC provides that I'm missing.

**Comment by jackquinlan** [comment]
Hi Mohsen, thanks for the comment! 
I mainly added tRPC because I enjoy building with it. Blueprint is just meant to be a starting point that you can customize. 

To make it easier for people to pick which technologies they want, do you think I should implement a few different versions that people can pick from?

**Comment by mohsen1** [comment]
It's your project and you should drive the direction it takes. I'm just asking questions. If you want my opinion, stay opinionated and build it further with your preferred tech stack. I'm already benefiting from your work! 

A few observations while browsing the code that you might want to address, which is not related to this issue:

* The seed script is not up to date with schema. A quick ChatGPT query can make a nice seed script for this.
* Jest testing infrastructure would be a nice addition 
* There is no TypeScript check script at root. I think making this into a [composite project](https://www.typescriptlang.org/docs/handbook/project-references.html) would be nice.  I noticed there are some existing type errors in master. `tailwind.config.ts` for example
* Having GitHub workflow for checking lint, ts and unit test out of the box would be nice
* Providing an example of RCS would be nice. For example, number of todo items in the nav can be suspended 
* **This might be a tough one** Having it ready to deploy to Vercel, where the preview environments can be auth'd. Since GitHub does not allow providing a wildcard for the OAuth callback, it needs to redirect (and set-cookie) back to the initial login (`NEXT_AUTH_URL`?) using the OAuth state parameter in the production deployments.  Edit: I noticed you added email login/signup. With that, the preview env can be auth'd. so this might not be necessary
