### ISSUE TITLE
Application error: a server-side exception has occurred (see the server logs for more information). Digest: 1199119462

### ISSUE THREAD

**Issue by JohnnyBDesign** [jackquinlan/blueprint#26]
Hey, been using this start-kit for my site and it's been great, but I just recently noticed both BluePrint and my site are sharing the same error message.

Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1199119462

<img width="783" alt="Screenshot 2024-02-02 at 12 52 07 PM" src="https://github.com/jackquinlan/blueprint/assets/88093712/1c0d077d-26cb-4590-9d4d-d39a0bd310d5">

Console reads:

Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 1199119462

Any ideas why this error is happening now after 30 days of steady deployment? Changes to 3rd party API's?

Thank you!

**Comment by JohnnyBDesign** [comment]
Seems to be an issue with tasks.

**Comment by jackquinlan** [comment]
Hi Johnny, sorry for the late reply, I had a super busy weekend. 
Thank you for bringing this to my attention. I am going to look into this tonight. I will let you know what I find.

**Comment by jackquinlan** [comment]
Hi Johnny, I have fixed the issue, you should be all set now. It was the .getUserTasks tRPC query. I have since replaced that query with regular server component db queries (in nav.tsx and todolist.tsx).

Hope this helps! Thanks for your help pointing this out! I hope you keep getting value from Blueprint! Let me know if you have any suggestions.

**Comment by JohnnyBDesign** [comment]
Hey Jack,

Thanks for pointing out the issue and resolving it.

Blueprint has been amazing thus far, I appreciate you taking the time to put this together!

All the best!
